### ISSUE TITLE
[Enhancement] Make the Animation Smoother

### ISSUE THREAD

**Issue by Shodelat** [KrLite/Warp-Zone#4]
Really cool mod I want to play with but the animation looks veeery jerky. I tried all versions of the mod but there's no difference :(

**Comment by KrLite** [comment]
It is indeed kinda laggy. I will figure that out.

**Comment by KrLite** [comment]
I made some improvements to the newer versions and I think it is indeed smoother, despite still being a little clumsy when the FOV is too big or too small. However, the FOV is now configurable. This problem seems to be solved, since I don't know how to further improve this mod anymore. But I hope this tiny animation still brings you joy in some extend.

**Comment by Shodelat** [comment]
> I made some improvements to the newer versions and I think it is indeed smoother, despite still being a little clumsy when the FOV is too big or too small. However, the FOV is now configurable. This problem seems to be solved, since I don't know how to further improve this mod anymore. But I hope this tiny animation still brings you joy in some extend.

just tested it. what do I do if it is still pretty laggy?😭 feels "ok" only when set 102 or 98

https://github.com/KessokuTeaTime/Warp-Zone/assets/160461810/6db4e7f8-f7fd-44ef-a605-baa6804a4234

**Comment by Shodelat** [comment]
> > I made some improvements to the newer versions and I think it is indeed smoother, despite still being a little clumsy when the FOV is too big or too small. However, the FOV is now configurable. This problem seems to be solved, since I don't know how to further improve this mod anymore. But I hope this tiny animation still brings you joy in some extend.
> 
> what do I do if it is still pretty laggy?😭 feels "ok" only when set 102 or 98
> 
>  bandicam.2024-06-19.01-28-59-472.mp4

**Comment by KrLite** [comment]
> > I made some improvements to the newer versions and I think it is indeed smoother, despite still being a little clumsy when the FOV is too big or too small. However, the FOV is now configurable. This problem seems to be solved, since I don't know how to further improve this mod anymore. But I hope this tiny animation still brings you joy in some extend.
> 
> 
> 
> just tested it. what do I do if it is still pretty laggy?😭 feels "ok" only when set 102 or 98
> 
> 
> 
> https://github.com/KessokuTeaTime/Warp-Zone/assets/160461810/6db4e7f8-f7fd-44ef-a605-baa6804a4234
> 
> 
> 
> 

That is the current result. It's the smoothest I can achieve using the approach of modifying FOV. For further improvements, shaders may have to be used. But that is not in my current plan. Maybe there will be updates in the future!
